//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAEZBlocker.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YAEZBlocker.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Banner Ads.
        /// </summary>
        public static string BlockBannersCheckboxText {
            get {
                return ResourceManager.GetString("BlockBannersCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may need to restart Spotify or your computer for this setting to take effect..
        /// </summary>
        public static string BlockBannersRestart {
            get {
                return ResourceManager.GetString("BlockBannersRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling/Disabling this option requires Administrator privileges.
        ///
        ///Please reopen YAEZBlocker with &quot;Run as Administrator&quot;..
        /// </summary>
        public static string BlockBannersUAC {
            get {
                return ResourceManager.GetString("BlockBannersUAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAEZBlocker is hidden. Double-click this icon to restore..
        /// </summary>
        public static string HiddenNotify {
            get {
                return ResourceManager.GetString("HiddenNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string NaText {
            get {
                return ResourceManager.GetString("NaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify ads will not be muted if YAEZBlocker is not running.
        ///
        ///Are you sure you want to exit?.
        /// </summary>
        public static string OnExitMessageBox {
            get {
                return ResourceManager.GetString("OnExitMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAEZBlocker Version: {0}
        ///Spotify Version: {1}.
        /// </summary>
        public static string ReportProblemClipboard {
            get {
                return ResourceManager.GetString("ReportProblemClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please leave a comment clearly describing your problem.
        ///
        ///Paste this information (already copied to your clipboard):
        ///YAEZBlocker Version: {0}
        ///Spotify Version: {1}.
        /// </summary>
        public static string ReportProblemMessageBox {
            get {
                return ResourceManager.GetString("ReportProblemMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Spotify with YAEZBlocker.
        /// </summary>
        public static string SpotifyCheckboxText {
            get {
                return ResourceManager.GetString("SpotifyCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start YAEZBlocker on Login.
        /// </summary>
        public static string StartupCheckboxText {
            get {
                return ResourceManager.GetString("StartupCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string StatusLabelLoadingText {
            get {
                return ResourceManager.GetString("StatusLabelLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muting.
        /// </summary>
        public static string StatusMuting {
            get {
                return ResourceManager.GetString("StatusMuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify not found.
        /// </summary>
        public static string StatusNotFound {
            get {
                return ResourceManager.GetString("StatusNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify is paused.
        /// </summary>
        public static string StatusPaused {
            get {
                return ResourceManager.GetString("StatusPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing.
        /// </summary>
        public static string StatusPlaying {
            get {
                return ResourceManager.GetString("StatusPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ToolStripExit {
            get {
                return ResourceManager.GetString("ToolStripExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show YAEZBlocker Window.
        /// </summary>
        public static string ToolStripOpen {
            get {
                return ResourceManager.GetString("ToolStripOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open YAEZBlocker Website.
        /// </summary>
        public static string ToolStripWebsite {
            get {
                return ResourceManager.GetString("ToolStripWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error checking for update..
        /// </summary>
        public static string UpgradeErrorMessageBox {
            get {
                return ResourceManager.GetString("UpgradeErrorMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a newer version of YAEZBlocker available. Would you like to upgrade?.
        /// </summary>
        public static string UpgradeMessageBox {
            get {
                return ResourceManager.GetString("UpgradeMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Volume Control.
        /// </summary>
        public static string VolumeMixerButtonText {
            get {
                return ResourceManager.GetString("VolumeMixerButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open Volume Control.
        /// </summary>
        public static string VolumeMixerOpenError {
            get {
                return ResourceManager.GetString("VolumeMixerOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Problem.
        /// </summary>
        public static string WebsiteLinkText {
            get {
                return ResourceManager.GetString("WebsiteLinkText", resourceCulture);
            }
        }
    }
}
